package com.logimarui.shared.authorization;

public enum PermissionCode {

    // AUTHENTICATION / USERS
    AUTHENTICATION_USER_READ,
    AUTHENTICATION_USER_CREATE,
    AUTHENTICATION_USER_UPDATE,
    AUTHENTICATION_USER_DISABLE,
    AUTHENTICATION_USER_ENABLE,
    AUTHENTICATION_USER_PASSWORD_RESET_LINK_GENERATE,
    AUTHENTICATION_USER_TEMPORARY_PASSWORD_GENERATE,

    // AUTHORIZATION / ROLES
    AUTHORIZATION_ROLE_READ,
    AUTHORIZATION_ROLE_CREATE,
    AUTHORIZATION_ROLE_UPDATE,
    AUTHORIZATION_ROLE_DISABLE,
    AUTHORIZATION_ROLE_ENABLE,
    AUTHORIZATION_ROLE_DELETE,

    // AUTHORIZATION / PERMISSIONS
    AUTHORIZATION_PERMISSION_READ,
    AUTHORIZATION_PERMISSION_ASSIGN,
    AUTHORIZATION_PERMISSION_REVOKE,

    // AUTHORIZATION / USER ROLES
    AUTHORIZATION_USER_ROLE_READ,
    AUTHORIZATION_USER_ROLE_ASSIGN,
    AUTHORIZATION_USER_ROLE_REVOKE,

    // HEALTH
    HEALTH_MEDICAL_PROFILE_UPDATE,
    HEALTH_MEDICAL_PROFILE_READ,

    // MEMBERSHIP /
    MEMBERSHIP_MEMBERSHIP_REQUEST_READ,
    MEMBERSHIP_MEMBERSHIP_REQUEST_APPROVE,
    MEMBERSHIP_MEMBERSHIP_REQUEST_REJECT,
    MEMBERSHIP_MEMBERSHIP_REQUEST_INVITE_RESEND
}