package com.logimarui.reposicoes.core.domain.enums;

public enum ReplenishmentStatus {
    MOTORISTA_ESCREVENDO,
    MOTORISTA_CANCELOU,


    AGUARDANDO_VALIDACAO_MONITORAMENTO,
    REPOSICAO_APROVADA_PELO_MONITORAMENTO,
    REPOSICAO_RECUSADA_PELO_MONITORAMENTO,


    AGUARDANDO_VALIDACAO_ESTOQUE,
    REPOSICAO_APROVADA_PELO_ESTOQUE,
    REPOSICAO_RECUSADA_PELO_ESTOQUE,

    REPOSICAO_AGUARDANDO_LANCAMENTO,

    ENVIO_SOLICITADO,
    FATURADO,
    EM_ROTA,
    ENTREGUE

}
