# ========= SERVER =========
server.port=8080

# ========= WRITE DB (DEFAULT / JPA) =========
spring.datasource.url=jdbc:mysql://192.168.0.112:3306/logimarui?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=logimarui-core-api
spring.datasource.password=Imarui@25
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (WRITE)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========= READ DB (LEGADO) =========
app.datasource.read.jdbc-url=jdbc:mysql://192.168.0.112:3306/diretorio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
app.datasource.read.username=logimarui-core-api
app.datasource.read.password=Imarui@25
app.datasource.read.driver-class-name=com.mysql.cj.jdbc.Driver
