# ========= SERVER =========
server.port=${CORE_API_PORT:80}
spring.profiles.active=dev
app.server.base-url=http://localhost:${server.port}

# ========= WRITE DB (DEFAULT / JPA) =========
spring.datasource.url=jdbc:mysql://192.168.0.43:3306/logimarui?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=logimarui-core-api
spring.datasource.password=Imarui@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (WRITE)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========= READ DB (LEGADO) =========
app.datasource.read.jdbc-url=jdbc:mysql://192.168.0.43:3306/diretorio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
app.datasource.read.username=logimarui-core-api
app.datasource.read.password=Imarui@2026
app.datasource.read.driver-class-name=com.mysql.cj.jdbc.Driver

# ========= SECURITY =========
# ========= JWT =========
security.jwt.secret=logimarui-auth-jwt-secret-32-bytes-key!!
security.jwt.access-token-expiration-seconds=3600
security.jwt.issuer=logimarui-auth

# ========= FRONTEND =========
app.frontend.url=${APP_FRONTEND_URL:http://127.0.0.1:8091}

# ========= AUTH/TTL =========
security.auth.refresh-token-ttl=7d
security.auth.session-ttl=7d
security.auth.password-recovery-request-ttl=7d
security.auth.password-change-challenge-ttl=10m
membership.activation-token-ttl=72h

# ========= BOOTSTRAP/INICIAL =========
security.bootstrap.admin.enabled=true
security.bootstrap.admin.name=Administrador Dev
security.bootstrap.admin.birth-date=2000-01-01
security.bootstrap.admin.email=admin.dev@logimarui.local
security.bootstrap.admin.cpf=12345678909
security.bootstrap.admin.password=admin123
security.bootstrap.admin.phone-number=11999999999
security.bootstrap.admin.role-name=ADMIN

# ========= CORS =========
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:80,http://127.0.0.1:80,http://localhost,http://127.0.0.1,http://localhost:81,http://127.0.0.1:81,http://localhost:3000,http://127.0.0.1:3000,http://localhost:8091,http://127.0.0.1:8091,http://localhost:8191,http://127.0.0.1:8191}

# ========= SWAGGER =========
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
