package com.logimarui.authorization.core.domain.enums;

public enum PermissionCode {

    // AUTHENTICATION / USERS
    AUTH_USER_READ,
    AUTH_USER_CREATE,
    AUTH_USER_UPDATE,
    AUTH_USER_DISABLE,
    AUTH_USER_ENABLE,

    // AUTHENTICATION / EMPLOYEES
    AUTH_EMPLOYEE_NAME_READ,

    // AUTHORIZATION / ROLES
    AUTHZ_ROLE_READ,
    AUTHZ_ROLE_CREATE,
    AUTHZ_ROLE_UPDATE,
    AUTHZ_ROLE_DELETE,

    // AUTHORIZATION / PERMISSIONS
    AUTHZ_PERMISSION_READ,
    AUTHZ_PERMISSION_ASSIGN,
    AUTHZ_PERMISSION_REVOKE,

    // AUTHORIZATION / USER ROLES
    AUTHZ_USER_ROLE_ASSIGN,
    AUTHZ_USER_ROLE_REVOKE,

    // GATEWAY ADMIN / SERVICES
    GATEWAY_SERVICE_RUNTIME_READ,
    GATEWAY_SERVICE_START,
    GATEWAY_SERVICE_STOP,
    GATEWAY_SERVICE_RESTART,
    GATEWAY_SERVICE_START_ALL,
    GATEWAY_SERVICE_STOP_ALL,
    GATEWAY_SERVICE_REFRESH
}